name: RSpec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ "3.0", "3.2", "3.4", "3.5, "head", "jruby-head" ]

    steps:
    - uses: actions/checkout@v4
    - name: Remove Gemfile.lock
      run: rm Gemfile.lock || true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rspec --exclude-pattern "spec/contract/**/*_spec.rb"
